Update VisualStudioCode.gitignore
toptal/gitignore pull request #325
Opened 2020-08-13 15:35 UTC by martinVyoo

All of these files are user specific, they should not be included by default
VisualStudioCode will include a functionality in the future to sync the settings separately
https://github.com/microsoft/vscode/issues/2743

# Pull Request

Thank you for contributing to @dvcs/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ X] Template - Update existing `.gitignore` template

## Details

The removed files in the gitignore are user/environment specific, they should not be included in the git repository by default, since other contributors of the repository will have their settings being overwritten by what is in the git

VisualStudioCode will include a functionality in the future to separately sync settings https://github.com/microsoft/vscode/issues/2743

But even without that functionality, these files should not be included by default and rather be added by the user if he wants to add them to their repository

2020-09-04 14:17 UTC, WildCard65 requested changes

2020-09-04 14:17 UTC, WildCard65 commented on templates/VisualStudioCode.gitignore
> -!.vscode/launch.json
These two files should remain included as they're workspace/project specific, NOT user specific.

2020-09-04 14:25 UTC, martinVyoo commented on templates/VisualStudioCode.gitignore
> -!.vscode/launch.json
I think I can agree on this, as long as information written in these files do not contain information specific to a user's environment (in which case they are using these files wrong)

2020-09-04 14:29 UTC, WildCard65 approved these changes
These look good to me, though I'm an outside user for this.

2020-11-05 13:13 UTC, gnechita-toptal commented
@martinVyoo Thanks for your contribution.

2020-11-05 13:13 UTC, merged