feat: ignore Storybook build folder for Node
toptal/gitignore pull request #366
Opened 2021-02-01 15:38 UTC by caedes

# Pull Request

Thank you for contributing to @dvcs/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

*replace this section with links and/or info about the proposed request*

2021-02-01 15:39 UTC, caedes commented
Seems like it was override by a [previous commit](https://github.com/toptal/gitignore/commit/3c8f56ca701ab051f10f1ea6af66cd708f63b39b#diff-be95ea910b23ee1a6c80490c9e037c4f4b1842ed7c514ec716f483e8e189542d). Maybe because I was treating different tech on the same config file IDK.

2021-02-01 16:24 UTC, quibaritaenperdresatrompe requested changes

2021-02-01 16:24 UTC, quibaritaenperdresatrompe commented on templates/Node.gitignore
> +# Storybook build outputs
It seems that the output directory is `storybook-static/` cf. https://github.com/storybookjs/storybook/blob/c61b404a624d1b18027330906e7cf9000043379e/lib/cli/src/generate.ts#L85

2021-02-01 16:35 UTC, caedes commented on templates/Node.gitignore
> +# Storybook build outputs
Done, thx!

2021-02-01 16:37 UTC, quibaritaenperdresatrompe approved these changes

2021-03-11 01:36 UTC, merged

2021-03-11 01:37 UTC, gobr commented
@caedes @quibaritaenperdresatrompe thanks!