Ignore dotenv in dart
toptal/gitignore pull request #399
Opened 2021-06-12 04:41 UTC by Manoj-Paramsetti

# Pull Request

### Update

- [x] Template - Update existing `Dart.gitignore` template

## Details

**Reasons for making this change:**
Ignoring dotenv files to avoid leaking secrets on Github

**Links to documentation supporting these rule changes:**
Reason for ignoring the dotenv file on GitHub
https://blog.gitguardian.com/secrets-api-management/#git-ignore
dotenv package on pub.dev
https://pub.dev/packages/flutter_dotenv

## Related pull request in Github/gitignore - (Created by me)
[#3709-Github](https://github.com/github/gitignore/pull/3709)

2021-08-03 16:51 UTC, filipechagas reviewed
Thank you for contributing @Manoj-Paramsetti
I've left a comment for your appreciation.
Also, please use a patch file instead of changing main `.gitignore` one. Refer to our documentation for more information: https://github.com/toptal/gitignore#files

2021-08-09 08:20 UTC, Manoj-Paramsetti commented on templates/Dart.gitignore
> +.env.test
some people use `.env.example` to show their environment file structure so I used `.env` and `.env.test` separately

2021-08-10 02:41 UTC, Manoj-Paramsetti commented
> Thank you for contributing @Manoj-Paramsetti
> I've left a comment for your appreciation.
> Also, please use a patch file instead of changing main `.gitignore` one. Refer to our documentation for more information: https://github.com/toptal/gitignore#files

Okay, I will make those changes

2021-08-10 02:51 UTC, Manoj-Paramsetti commented on templates/Dart.gitignore
> +.env.test
@filipechagas I saw that the changes you requested is already exist in this repository

2021-08-10 02:55 UTC, Manoj-Paramsetti commented on templates/Dart.gitignore
> +.env.test
I think ignoring only `.env` is enough for environment file

2021-08-20 12:55 UTC, filipechagas requested changes
@Manoj-Paramsetti Can you please make it a `.patch` instead of `.gitignore`. 
This will also fix merging conflicts.

2021-08-20 14:01 UTC, Manoj-Paramsetti commented
> @Manoj-Paramsetti Can you please make it a `.patch` instead of `.gitignore`.
> This will also fix merging conflicts.

@filipechagas Updated my commit. You can check now

2021-09-24 14:11 UTC, deniskaber approved these changes

2021-09-27 12:55 UTC, merged