Support VSCode Project snippet scope
toptal/gitignore pull request #412
Opened 2021-08-25 05:59 UTC by selenehyun

And Fix missing EOF line instead of reporting issue

# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

*replace this section with links and/or info about the proposed request*

2021-09-27 14:34 UTC, deniskaber requested changes
Thank you for contributing, @selenehyun! I added some comments that need to be addressed. 

I would also suggest to move changes related to line-endings to be a separate pull-request as you already have VSCode as a title to this PR.

2021-09-27 14:34 UTC, deniskaber commented on templates/VisualStudioCode.gitignore
> +!.vscode/*.code-snippets
This change should be placed in a `.patch` file, so that it won't be overwritten after sync with github/gitignore repo

2021-09-28 01:57 UTC, selenehyun commented on templates/ThinkPHP.gitignore-e
> +# gitignore template for ThinkPHP v3.2.3
Removed unnecessary changes as per your comment!

2021-09-28 01:58 UTC, selenehyun commented on templates/VisualStudioCode.gitignore
> +!.vscode/*.code-snippets
Oops, I forgot to edit the patch file!
Please check the modified changes

2021-11-01 09:47 UTC, deniskaber approved these changes

2021-11-01 09:47 UTC, merged