Update Erlang.gitignore
toptal/gitignore pull request #437
Opened 2021-12-09 12:00 UTC by gilbertwong96

##  Update

- [x] Template - Update existing `.gitignore` template

## Details

The rebar3 is the default Erlang build tool. Sometimes it would
generate rebar3.crashdump in the workspace. The rebar3.crashdump should
be excluded from project.

2021-12-29 06:41 UTC, konstrybakov requested changes
Hello @gilbertwong96! Thank you for taking the time to contribute! 

`Erlang.gitignore` is synced from https://github.com/github/gitignore/blob/main/Erlang.gitignore

Please add your changes to an `Erlang.patch` file, for them not to be overwritten during the next sync

2022-01-31 19:29 UTC, filipechagas commented
Hi @gilbertwong96! 
Can you please check @konstrybakov 's comment and make the changes?

2022-02-02 15:37 UTC, gilbertwong96 commented
> Hi @gilbertwong96!
> Can you please check @konstrybakov 's comment and make the changes?

Of course. Sorry for late reply.

2022-02-02 15:40 UTC, gilbertwong96 commented
Done. @konstrybakov @filipechagas

2022-02-24 17:56 UTC, filipechagas approved these changes

2022-02-24 17:57 UTC, merged