Created CircuitPython.gitignore
toptal/gitignore pull request #444
Opened 2022-02-02 21:55 UTC by bhavesh-k

# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [x] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details

*replace this section with links and/or info about the proposed request*

2022-02-04 13:35 UTC, filipechagas requested changes
Thanks for contributing!

As soon as the requested changes are applied, we'll be happy to accept the PR.

2022-02-04 13:35 UTC, filipechagas commented on templates/CircuitPython.gitignore
> +.fseventsd/
`.Trashes` and `.fseventsd` are macOS related. They're being ignored by `macOS.gitignore`. I see that `.metadata_never_index` is also macOS related so you may want to add it to a `macOS.patch` file instead.

2022-02-16 20:47 UTC, bhavesh-k commented on templates/CircuitPython.gitignore
> +.fseventsd/
@filipechagas Hi, do you need more information on this? I hope my explanation was clear - please let me know if not

2022-02-17 13:11 UTC, filipechagas approved these changes

2022-02-17 13:11 UTC, filipechagas commented on templates/CircuitPython.gitignore
> +.fseventsd/
Thank you for giving me context @bhavesh-k ! It makes sense.

2022-02-24 17:57 UTC, merged