Update NextJs gitignore
toptal/gitignore pull request #449
Opened 2022-03-23 14:06 UTC by mriios

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details
Update to NextJS gitignore, including default files and routes.

2022-04-22 15:35 UTC, filipechagas requested changes
Hi and thank you for contributing.

I've left a few suggestions.

2022-04-22 15:35 UTC, filipechagas commented on templates/NextJS.gitignore
> +/Build
```suggestion
/build
```

2022-04-22 15:35 UTC, filipechagas commented on templates/NextJS.gitignore
> +.vercel
```suggestion
.vercel

#editors
.idea
.vscode
```

2022-04-22 15:35 UTC, filipechagas commented on templates/NextJS.gitignore
> +.vercel
Can you also please fix missing EOL?

2022-06-02 00:42 UTC, mriios commented on templates/NextJS.gitignore
> +.vercel
@filipechagas do we want to add the editors even if they're in their own gitignore?

2022-06-15 18:38 UTC, filipechagas commented on templates/NextJS.gitignore
> +.vercel
It was just a suggestion, as you may usually find these entries in NextJS gitignore files. But I agree with you. Lets leave the editors out.

Please fix EOL and we're good to merge 🙂

2022-06-20 12:25 UTC, filipechagas approved these changes

2022-07-18 11:19 UTC, merged