Add Azure settings
toptal/gitignore pull request #457
Opened 2022-04-25 11:32 UTC by softwaredevelop

# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

Add [Azure Toolkit for IntelliJ](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij) settings

2022-04-27 20:50 UTC, iatanas0v approved these changes

2022-04-28 12:14 UTC, filipechagas requested changes
Hi and thank you for contributing! 👋 

`JetBrains.gitignore` is morrored from Github, which means any changes to it will be overwritten by the CI. You can make additions using a `JetBrains.patch` file instead.

https://github.com/toptal/gitignore/blob/73c93f8be2912e004c7fa6d17f0a8369bbf178bc/.moban.yaml#L108

2022-04-30 10:39 UTC, softwaredevelop commented
I added Azure Toolkit for IntelliJ plugin ignore to JetBrains.patch

2022-05-03 11:03 UTC, filipechagas approved these changes

2022-05-19 11:09 UTC, yusufzmly approved these changes
Hello @softwaredevelop , Thank you for taking the time to contribute to Gitignore!

2022-05-19 11:09 UTC, merged