Mill
toptal/gitignore pull request #468
Opened 2022-07-19 21:00 UTC by jaacko-torus

# Pull Request

- [x] Template - New `.gitignore` template

## Details

mill's [homepage](com-lihaoyi.github.io/mill/)

Mill is a build tool primarily targeted at the scala language.

[justification for gitignore source](https://github.com/com-lihaoyi/mill/discussions/1956#discussioncomment-3169086).

2022-07-21 14:39 UTC, Vitahabtc commented
> # Pull Request
> 
> - [x] Template - New `.gitignore` template
> 
> ## Details
> 
> mill's [homepage](com-lihaoyi.github.io/mill/)
> 
> Mill is a build tool primarily targeted at the scala language.
> 
> [justification for gitignore source](https://github.com/com-lihaoyi/mill/discussions/1956#discussioncomment-3169086).

2022-07-21 14:40 UTC, Vitahabtc commented
> > # Pull Request
> > 
> > - [x] Template - New `.gitignore` template
> > 
> > ## Details
> > 
> > mill's [homepage](com-lihaoyi.github.io/mill/)
> > 
> > Mill is a build tool primarily targeted at the scala language.
> > 
> > [justification for gitignore source](https://github.com/com-lihaoyi/mill/discussions/1956#discussioncomment-3169086).
> 
>

2022-07-21 14:51 UTC, filipechagas requested changes
Hi @jaacko-torus 👋 
Thanks for contributing!

Can you please fix the missing EOL?

2022-08-22 11:38 UTC, filipechagas approved these changes

2022-08-22 11:39 UTC, merged