Update TwinCAT3.gitignore
toptal/gitignore pull request #497
Opened 2022-11-10 07:50 UTC by Tc-KGu

ignore subfolder which includes binaries or libraries. ignore VS folder
ignore System Manager backup files

# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details

*replace this section with links and/or info about the proposed request*

2022-11-10 11:48 UTC, alexmcode requested changes
Hi @Tc-KGu and thanks for your contribution! I did leave a few comments and some changes requested.

Also, please check one of the checkboxes in the PR template so we know in what category your changes fall. Thank you again!

2022-11-10 11:48 UTC, alexmcode commented on templates/TwinCAT3.gitignore
> -*.tmc
I think this change should be undone in order for this gitignore to be useful in more cases. If these are the changes that would work for you currently maybe this can be done in your local repo/environment. WDYT?

2022-11-10 11:48 UTC, alexmcode commented on templates/TwinCAT3.gitignore
> -#
Please leave this in as it links to the original decision process PR for how this file is structured.

2022-11-10 11:48 UTC, alexmcode commented on templates/TwinCAT3.gitignore
> +**/.vs/
This is a visual studio specific file and it's already ignored in the [vs gitginore file](https://github.com/github/gitignore/blob/main/VisualStudio.gitignore#L36)

Maybe using also the vs gitignore file and combine the 2 in a single one on your repo?

2022-11-10 12:19 UTC, alexmcode commented
@Tc-KGu after a closer look into this PR it seems this file is mirrored from the upstream https://github.com/github/gitignore/blob/main/TwinCAT3.gitignore though, so changing it will not have any effect, as it will be rewritten by the CI.

You [can use](https://github.com/toptal/gitignore#files) a .patch file instead.

Also, you can open a PR on the upstream file if you wish to apply these exact changes.

Once you make the change, we'll be happy to merge your contribution!

2022-11-14 15:20 UTC, Tc-KGu commented on templates/TwinCAT3.gitignore
> -*.tmc
No, this change is important. If you do not have the tmc file, you will lose the process image, which will cause some problems in the engineering workflow.

2023-01-02 21:16 UTC, filipechagas commented
Hey @Tc-KGu , thank you again for contributing!

There are a couple of comments from @alexmcode that have yet to be appreciated. Could you please take another look?

Also, removing things from files that are mirrored [from the upstream](https://github.com/github/gitignore/blob/main/TwinCAT3.gitignore) doesn't work. `.patch` files can [extend mirrored files, but removing is not supported](https://github.com/toptal/gitignore#files). If you really think these lines should be removed, we recommend opening a PR in the upstream repository.

2023-02-16 02:00 UTC, closed without merging