Added CDK gitignore
toptal/gitignore pull request #512
Opened 2023-01-13 21:33 UTC by Wingjam

# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [x] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details

Create .gitignore template for [AWS CDK](https://aws.amazon.com/cdk/)

This is from the default .gitignore when using the AWS CDK CLI to create a new project and selecting typescript as primary language : https://github.com/aws/aws-cdk/blob/main/packages/aws-cdk/lib/init-templates/app/typescript/.template.gitignore

2023-01-19 06:26 UTC, Reem-Dalal approved these changes

2023-01-19 12:02 UTC, filipechagas requested changes
Thank you for contributing, @Wingjam !

I see this file is already present in the upstream https://github.com/github/gitignore/blob/main/community/AWS/CDK.gitignore

Instead having an untracked duplicate here, WDYT about just adding to https://github.com/toptal/gitignore/blob/master/.moban.yaml and have it automatically synced by the CI?

2023-01-22 23:03 UTC, Wingjam commented
Oh didn't saw this. Nice catch!
I think we can then close this PR and im gonna create a new one for the modification of [.moban.yaml](https://github.com/toptal/gitignore/blob/master/.moban.yaml)

2023-01-23 06:55 UTC, konstrybakov commented
Thank you @Wingjam! I'll be on the lookout for the next one!

2023-01-23 06:55 UTC, closed without merging