Update AL.gitignore
toptal/gitignore pull request #514
Opened 2023-01-19 11:02 UTC by EmilDamsbo

### Update

- [x] Template - Update existing `.gitignore` template

## Details
I am updating the AL Language gitignore because it is missing a few things.
The Rapid Application Development file and licenses should not be kept in source control.

2023-01-19 12:05 UTC, filipechagas requested changes
Thank you for contributing, @EmilDamsbo !

I see that these changes are already present in the upstream https://github.com/github/gitignore/blob/main/AL.gitignore

WDYT of just adding `AL.gitignore` to https://github.com/toptal/gitignore/blob/master/.moban.yaml and have it automatically synced by the CI?

2023-01-19 16:18 UTC, EmilDamsbo commented
@filipechagas The requested changes have been completed.

2023-01-20 08:55 UTC, konstrybakov approved these changes

2023-01-20 17:21 UTC, filipechagas approved these changes

2023-01-20 17:22 UTC, filipechagas approved these changes

2023-01-20 17:22 UTC, merged