Add new tempate FastAPI
toptal/gitignore pull request #534
Opened 2023-06-28 21:51 UTC by balexandermunoz

### New

- [x] Template - New `.gitignore` template

## Details

More information in [FastAPI .gitignore](https://github.com/tiangolo/fastapi/blob/master/.gitignore)

2023-06-30 07:17 UTC, konstrybakov requested changes
Hi @balexandermunoz,

First of all, thank you for your contribution to our project.

However, I noticed that your suggested .gitignore file seems to be a direct copy from the fastapi repository. While some of these ignored paths and files are relevant for FastAPI projects, not all of them are specifically related to the framework.

The purpose of this FastAPI.gitignore file should be to exclude files and directories that are specifically generated by the FastAPI framework and which we typically don't want to include in version control.

Here's a list of entries from your suggestion that aren't specific to FastAPI:

```
.idea
.ipynb_checkpoints
.vscode
dist
site
.coverage
coverage.xml
.netlify
log.txt
Pipfile.lock
env3.*
env
docs_build
site_build
venv
docs.zip
```

While these entries are often useful to ignore in many Python projects, they are not specifically generated by FastAPI.

I kindly ask you to revise your PR to only include entries that are specifically related to FastAPI.

Thank you for your understanding and your help in keeping our project clean and well-organized.

2023-06-30 07:17 UTC, konstrybakov commented on templates/FastAPI.gitignore
> +.idea
I think this isn't specific to FastAPI

2023-06-30 07:17 UTC, konstrybakov commented on templates/FastAPI.gitignore
> +.ipynb_checkpoints
I think this isn't specific to FastAPI, it relates to Jupyter Notebooks, right?

2023-06-30 07:17 UTC, konstrybakov commented on templates/FastAPI.gitignore
> +.vscode
Not related to FastAPI

2023-06-30 07:17 UTC, konstrybakov commented on templates/FastAPI.gitignore
> +site
Not strictly related to FastAPI

2023-06-30 07:17 UTC, konstrybakov commented on templates/FastAPI.gitignore
> +.netlify
same here

2023-06-30 21:30 UTC, balexandermunoz commented
Hi, thanks for the feedback.
The PR has been updated!

2023-07-04 07:14 UTC, konstrybakov reviewed
Upon further review, it seems that everything aside from test.db and archive.zip is accounted for in the Python .gitignore file provided here:

https://www.toptal.com/developers/gitignore/api/python

Given this, I would like to understand the purpose of the test.db and archive.zip files. How do they pertain to FastAPI?

Additionally, does FastAPI generate any specific files that should not be committed to version control?

2023-08-19 01:42 UTC, closed without merging